name: Lint & Test
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false # required on Windows
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@d583c34f0599d37dbac4a198b9c83201be380893 # v9.3.0
        with:
          skip-cache: true
      - name: Validate OpenAPI spec
        run: |
          npm install --global swagger-spec-validator@5.0.0
          swagger-spec-validator openapi/*.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      POSTGRES_USER: indexd_test
      POSTGRES_PASSWORD: indexd_test
      POSTGRES_DB: indexd_test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: indexd_test
          POSTGRES_PASSWORD: indexd_test
          POSTGRES_DB: indexd_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26"
      - name: Cache GeoLite2 database
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: GeoLite2-City.mmdb
          key: geolite2-city-mmdb-2026-04
      - name: Test
        uses: n8maninger/action-golang-test@0428e9495ddb18ad98c4fbbc385e63b6e7215a2f # v2.2.1
        with:
          args: -race;-failfast
